language: java
jdk:
- openjdk7
before_install:
  - ./scripts/installSkript.sh
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: LbOEmph3JxVwgs7Y0gJYU1Hl8Lidn+fcvnUYBIAHFvofog3QpF0RgxZQrnhrAlpS8wBGhTPITclxQtOfsXIcWpM5CQWyqqkyX4umNWOmFDSMAR1ZAdOZlpYTlc0m1Jd0slCOoPBX8ucMCbraFT0TDO6mNtgciozTDGWSUZz1YToS59L1GghTY+Zg2e8FW0MBGSqbWfuqELeJxeniBg+ShikecKUK2LG8LRUNcvASZxMFbraPEcXbDlr6cdIWIQhPkaUxx9Eekj8oEMKXwZqnb26AzThlwSoThl2bfK7XbMXCXAgHkr9ABFmqSnwI31tY01TqoSJ/sldaYtSDdUANw3WHak26SpxWKma7P9vgfOpv9nKNYYGJj9dzSAVIYRpjNpCo7FsIP/qUY4DlFBPG1K7ma/jhRwSAT6nCfjodQ57VwnQwQXtOA965p5oYHmbtToXe+aIkMd3Rw4WZHr3bEJqS/8GGQIVmZWjnZLBVVIEHTBZxKKaeAQnEaPjvonn670xytWAnMoBaOn0n5BMryzgGUb54j60TK8ole72furX2H+gpOlpEim6m23mXbjiAJ6Cdy2PKcXp/bS5m5K0QXW1QNts4KJpByMK7DgpgtTJ090Z/MADNnXmruCtfmERsKdgy5MuWeoIJmzwaXTkprzsLs0hrAAd79j7Iaud2s3M=
  file: target/MCJukebox.jar
  on:
    tags: true
